---
- name: Deploying Roboshop website using Ansible roles on AWS EC2 instance.
  hosts: aws
  become: yes

  # Setting common variables for all roles
  vars:
    app_id: roboshop
    app_user: roboshop
    app_group: roboshop
    app_home: /home/roboshop

  tasks:
    # Ensuring the application user exists globally for all services.
    # These tasks runs before the roles.
    - name: Ensure the common application user 'roboshop' exists.
      user:
        name: "{{ app_user }}"
        state: present

  roles:
    - rabbitmq
    - mysql
    - redis
    - mongodb
    - catalogue
    - user
    - cart
    - shipping
    - payment
    - frontend
