FROM rabbitmq:3-management
# FROM rabbitmq:3.10.5-management
# docker run -d --hostname my-rabbit --name rabbitmq2 -p 8080:15672 rabbitmq:3-management
# docker run -d --name rabbitmq -p 5672:5672 -p 15672:15672 rabbitmq:3-management
# guest:guest