# Headless service
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  clusterIP: None
  selector:
    app: rabbitmq-roboshop
  ports:
  - name: rabbitmq-tls
    protocol: TCP
    port: 5671
    targetPort: 5671
  - name: rabbitmq-amqp
    protocol: TCP
    port: 5672
    targetPort: 5672
  - name: management-plugin-tls
    protocol: TCP
    port: 15671
    targetPort: 15671
  - name: management-plugin-http
    protocol: TCP
    port: 15672
    targetPort: 15672
---

# statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: roboshop-rabbitmq
  labels:
    app: roboshop-rabbitmq
spec:
  serviceName: rabbitmq
  selector:
    matchLabels:
      app: rabbitmq-roboshop
  template:
    metadata:
      labels:
        app: rabbitmq-roboshop
    spec:
      containers:
      - name: rabbitmq-container
        image: sivaram0101/rabbitmq-roboshop:v1
        ports:
        - containerPort: 5671
        - containerPort: 5672
        - containerPort: 15671
        - containerPort: 15672
        env:
        - name: RABBITMQ_DEFAULT_USER
          value: roboshop
        - name: RABBITMQ_DEFAULT_PASS
          value: roboshop123
        volumeMounts:
        - name: rabbitmq-volume
          mountPath: /var/lib/rabbitmq
      volumes:
        - name: rabbitmq-volume
          persistentVolumeClaim:
            claimName: rabbitmq-pvc-0
---

# pvc
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rabbitmq-pvc-0
spec:
  storageClassName: roboshop-sc
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

# pv
apiVersion: v1
kind: PersistentVolume
metadata:
  name: rabbitmq-pv-0
spec:
  storageClassName: roboshop-sc
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /backup/rabbitmq
  persistentVolumeReclaimPolicy: Retain
---