# service:
apiVersion: v1
kind: Service
metadata:
  name: shipping
spec:
  selector:
    app: shipping-roboshop
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---

# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: roboshop-shipping
  labels:
    app: roboshop-shipping
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-roboshop
  template:
    metadata:
      labels:
        app: shipping-roboshop
    spec:
      containers:
      - name: shipping-container
        image: sivaram0101/shipping-roboshop:v1
        ports:
        - containerPort: 8080
        # resources:
        #   requests:
        #     memory: "300Mi"
        #     cpu: "300m"
        #   limits:
        #     memory: "500Mi"
        #     cpu: "500m"
        # startupProbe:
        #   tcpSocket:
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 5
        #   failureThreshold: 24
        # livenessProbe:
        #   tcpSocket:
        #     port: 8080
        #   periodSeconds: 30
        #   failureThreshold: 3
        # readinessProbe:
        #   tcpSocket:
        #     port: 8080
        #   periodSeconds: 10
        #   failureThreshold: 1
# probing mechanism with http:
        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 10
        #   successThreshold: 1
        #   failureThreshold: 2
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 15
        #   periodSeconds: 10
        #   successThreshold: 1
        #   failureThreshold: 2
        # startupProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 20
        #   periodSeconds: 10
        #   successThreshold: 1
        #   failureThreshold: 2
---